// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8xzQcQ679P-ITxzw74IZkJ5FDxERhI_E',
    appId: '1:79228092581:web:8e826766c972ad80634d4c',
    messagingSenderId: '79228092581',
    projectId: 'system-help',
    authDomain: 'system-help.firebaseapp.com',
    storageBucket: 'system-help.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXrj-_v884cf_OYtqvo6ULNMjoNAQlWmo',
    appId: '1:79228092581:android:2e86c58ba5892ba4634d4c',
    messagingSenderId: '79228092581',
    projectId: 'system-help',
    storageBucket: 'system-help.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4sLTOvEDvdqu83I1VPqS2awxB0Zt8RZg',
    appId: '1:79228092581:ios:bcb6e6461eb112dc634d4c',
    messagingSenderId: '79228092581',
    projectId: 'system-help',
    storageBucket: 'system-help.appspot.com',
    iosBundleId: 'com.example.systemHelp',
  );
}
